#!/bin/bash

# Generates C# bindings from Datadog iOS XCFrameworks using Objective Sharpie
#
# Usage:
#   ./generate-ios-bindings-sharpie.sh
#
# Prerequisite: Objective Sharpie must be installed
#   brew install objectivesharpie
#   -- or --
#   https://aka.ms/objective-sharpie
#
# This script ONLY binds Framework-Swift.h headers (the ObjC interface
# generated by the Swift compiler).  If a framework does not ship a
# Swift header it is skipped and a warning is logged.  Umbrella / plain-C
# headers (Framework.h) are never used because they produce incorrect
# bindings that silently diverge from the Swift API surface.

set -e

# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

ARTIFACTS_DIR="$PROJECT_ROOT/Datadog.MAUI.iOS.Binding/artifacts"
OUTPUT_DIR="$PROJECT_ROOT/Datadog.MAUI.iOS.Binding/Generated"
LOG_FILE="$OUTPUT_DIR/binding-warnings.log"

# ---------------------------------------------------------------------------
# Platform directory preference order
# Prefer the device slice for arm64 symbols; fall back to simulator.
# ---------------------------------------------------------------------------
PLATFORM_DIRS=(
    "ios-arm64_arm64e"
    "ios-arm64"
    "ios-arm64_x86_64-simulator"
)

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
if ! command -v sharpie &> /dev/null; then
    echo -e "${RED}Error: Objective Sharpie is not installed${NC}"
    echo "Install with:  brew install objectivesharpie"
    echo "  -- or --     https://aka.ms/objective-sharpie"
    exit 1
fi

echo -e "${CYAN}Objective Sharpie version: $(sharpie -v)${NC}"

if [ ! -d "$ARTIFACTS_DIR" ]; then
    echo -e "${RED}Error: Artifacts directory not found: $ARTIFACTS_DIR${NC}"
    echo -e "${YELLOW}Run ./download-ios-frameworks.sh first${NC}"
    exit 1
fi

# ---------------------------------------------------------------------------
# Xcode / SDK detection
#
# Try versioned Xcode installs first (15.x, 16.x, 26.x) then the default
# /Applications/Xcode.app.  Any Xcode that ships an iphoneos SDK will work;
# Sharpie 3.5+ is compatible with modern SDKs.
# ---------------------------------------------------------------------------
echo -e "${CYAN}Detecting Xcode / iOS SDK...${NC}"

XCODE_FOUND=false

for XCODE_PATTERN in /Applications/Xcode-15*.app /Applications/Xcode-16*.app /Applications/Xcode_26*.app /Applications/Xcode-26*.app /Applications/Xcode.app; do
    for XCODE_PATH in $XCODE_PATTERN; do
        if [ -d "$XCODE_PATH" ]; then
            XCODE_VERSION=$(defaults read "$XCODE_PATH/Contents/version" CFBundleShortVersionString 2>/dev/null || echo "unknown")
            echo -e "${GREEN}Using Xcode $XCODE_VERSION at $XCODE_PATH${NC}"
            export DEVELOPER_DIR="$XCODE_PATH/Contents/Developer"
            XCODE_FOUND=true
            break 2
        fi
    done
done

if [ "$XCODE_FOUND" = false ]; then
    echo -e "${YELLOW}Warning: No Xcode installation found, using xcode-select default${NC}"
fi

# Detect iOS SDK via Sharpie itself (more reliable than parsing xcodebuild)
SDK=$(sharpie xcode -sdks 2>/dev/null | grep '^sdk: iphoneos' | head -1 | awk '{print $2}')

if [ -z "$SDK" ]; then
    echo -e "${RED}Error: No iphoneos SDK found by Objective Sharpie${NC}"
    echo "Run 'sharpie xcode -sdks' to see available SDKs."
    exit 1
fi

echo -e "${GREEN}Using iOS SDK: $SDK${NC}"

# ---------------------------------------------------------------------------
# Frameworks to bind
# ---------------------------------------------------------------------------
FRAMEWORKS=(
    "DatadogCore"
    "DatadogInternal"
    "DatadogRUM"
    "DatadogLogs"
    "DatadogTrace"
    "DatadogCrashReporting"
    "DatadogSessionReplay"
    "DatadogWebViewTracking"
    "DatadogFlags"
    "OpenTelemetryApi"
)

# ---------------------------------------------------------------------------
# Prepare output
# ---------------------------------------------------------------------------
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
echo "# Binding Generation Warnings" > "$LOG_FILE"
echo "# Generated on $(date)" >> "$LOG_FILE"
echo "# Xcode: $(xcodebuild -version 2>/dev/null | head -1)" >> "$LOG_FILE"
echo "# SDK: $SDK" >> "$LOG_FILE"
echo "# Sharpie: $(sharpie -v)" >> "$LOG_FILE"
echo "" >> "$LOG_FILE"

echo ""

# ---------------------------------------------------------------------------
# Process each framework
# ---------------------------------------------------------------------------
TOTAL=${#FRAMEWORKS[@]}
CURRENT=0
SUCCESSFUL=0
SKIPPED=0
FAILED=0

for FRAMEWORK in "${FRAMEWORKS[@]}"; do
    ((CURRENT++))
    echo -e "${CYAN}[$CURRENT/$TOTAL] $FRAMEWORK${NC}"

    # --- Locate the framework directory (try each platform slice) ----------
    FRAMEWORK_PATH=""
    for PDIR in "${PLATFORM_DIRS[@]}"; do
        CANDIDATE="$ARTIFACTS_DIR/$FRAMEWORK.xcframework/$PDIR/$FRAMEWORK.framework"
        if [ -d "$CANDIDATE" ]; then
            FRAMEWORK_PATH="$CANDIDATE"
            break
        fi
    done

    if [ -z "$FRAMEWORK_PATH" ]; then
        MSG="$FRAMEWORK: xcframework directory not found under $ARTIFACTS_DIR/$FRAMEWORK.xcframework"
        echo -e "${RED}  ✗ $MSG${NC}"
        echo "ERROR: $MSG" >> "$LOG_FILE"
        ((FAILED++))
        echo ""
        continue
    fi

    # --- Locate the Swift-generated ObjC header -------------------------
    HEADERS_PATH="$FRAMEWORK_PATH/Headers"
    SWIFT_HEADER="$HEADERS_PATH/$FRAMEWORK-Swift.h"

    if [ ! -d "$HEADERS_PATH" ]; then
        MSG="$FRAMEWORK: No Headers/ directory in $FRAMEWORK_PATH (pure Swift module — no ObjC API surface)"
        echo -e "${YELLOW}  ⚠ SKIPPED — $MSG${NC}"
        echo "WARNING: $MSG" >> "$LOG_FILE"
        ((SKIPPED++))
        echo ""
        continue
    fi

    if [ ! -f "$SWIFT_HEADER" ]; then
        # List what IS in Headers/ for diagnostic context
        AVAILABLE_HEADERS=$(ls "$HEADERS_PATH" 2>/dev/null | tr '\n' ', ' | sed 's/,$//')
        MSG="$FRAMEWORK: Missing $FRAMEWORK-Swift.h (available headers: $AVAILABLE_HEADERS)"
        echo -e "${YELLOW}  ⚠ SKIPPED — Swift header not found${NC}"
        echo -e "${YELLOW}    Available headers: $AVAILABLE_HEADERS${NC}"
        echo -e "${YELLOW}    NOT falling back to umbrella header — it would produce incorrect bindings.${NC}"
        echo "WARNING: $MSG" >> "$LOG_FILE"
        ((SKIPPED++))
        echo ""
        continue
    fi

    echo -e "  Header: $FRAMEWORK-Swift.h"
    echo -e "  Slice:  $(basename "$(dirname "$FRAMEWORK_PATH")")"

    # --- Run Objective Sharpie -------------------------------------------
    FRAMEWORK_OUTPUT="$OUTPUT_DIR/$FRAMEWORK"
    mkdir -p "$FRAMEWORK_OUTPUT"

    SHARPIE_LOG="$FRAMEWORK_OUTPUT/sharpie.log"

    if sharpie bind \
        --output="$FRAMEWORK_OUTPUT" \
        --namespace="Datadog.iOS.$FRAMEWORK" \
        --sdk="$SDK" \
        -scope "$HEADERS_PATH" \
        "$SWIFT_HEADER" > "$SHARPIE_LOG" 2>&1; then
        SHARPIE_EXIT=0
    else
        SHARPIE_EXIT=$?
    fi

    # Count Sharpie warnings/errors
    WARN_COUNT=$(grep -c "warning:" "$SHARPIE_LOG" 2>/dev/null || true)
    WARN_COUNT=${WARN_COUNT:-0}
    ERR_COUNT=$(grep -c "error:" "$SHARPIE_LOG" 2>/dev/null || true)
    ERR_COUNT=${ERR_COUNT:-0}

    if [ -f "$FRAMEWORK_OUTPUT/ApiDefinitions.cs" ]; then
        API_LINES=$(wc -l < "$FRAMEWORK_OUTPUT/ApiDefinitions.cs" | tr -d ' ')
        echo -e "${GREEN}  ✓ ApiDefinitions.cs ($API_LINES lines)${NC}"

        if [ -f "$FRAMEWORK_OUTPUT/StructsAndEnums.cs" ]; then
            SE_LINES=$(wc -l < "$FRAMEWORK_OUTPUT/StructsAndEnums.cs" | tr -d ' ')
            echo -e "${GREEN}  ✓ StructsAndEnums.cs ($SE_LINES lines)${NC}"
        fi

        if [ "$WARN_COUNT" -gt 0 ]; then
            echo -e "${YELLOW}  ⚠ $WARN_COUNT Sharpie warning(s) — see $SHARPIE_LOG${NC}"
            echo "WARNING: $FRAMEWORK: Sharpie produced $WARN_COUNT warning(s)" >> "$LOG_FILE"
        fi

        ((SUCCESSFUL++))
    else
        MSG="$FRAMEWORK: Sharpie did not produce ApiDefinitions.cs (exit=$SHARPIE_EXIT, errors=$ERR_COUNT)"
        echo -e "${RED}  ✗ $MSG${NC}"
        echo -e "${RED}    See $SHARPIE_LOG for details${NC}"
        echo "ERROR: $MSG" >> "$LOG_FILE"
        ((FAILED++))
    fi

    echo ""
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}Summary${NC}"
echo -e "${CYAN}========================================${NC}"
echo -e "${GREEN}  Successful: $SUCCESSFUL${NC}"
echo -e "${YELLOW}  Skipped:    $SKIPPED (missing Swift headers — see warnings log)${NC}"
echo -e "${RED}  Failed:     $FAILED${NC}"
echo -e "${CYAN}  Total:      $TOTAL${NC}"
echo ""
echo -e "${CYAN}Output:   $OUTPUT_DIR${NC}"
echo -e "${CYAN}Warnings: $LOG_FILE${NC}"

if [ "$SKIPPED" -gt 0 ] || [ "$FAILED" -gt 0 ]; then
    echo ""
    echo -e "${YELLOW}Warnings & errors:${NC}"
    grep -E "^(WARNING|ERROR):" "$LOG_FILE" | while IFS= read -r line; do
        echo "  $line"
    done
fi

echo ""
echo -e "${CYAN}Next steps:${NC}"
echo "1. Review generated files in $OUTPUT_DIR/"
echo "2. Look for [Verify] attributes that need manual attention"
echo "3. Copy bindings into per-framework ApiDefinition.cs files"
echo "4. Build: dotnet build Datadog.MAUI.iOS.Binding/"

exit 0
