#!/bin/bash

# Generates C# bindings from Datadog iOS XCFrameworks using Objective Sharpie
#
# Usage:
#   ./generate-ios-bindings-sharpie.sh
#
# Prerequisite: Objective Sharpie must be installed
#   brew install objectivesharpie
#   -- or --
#   https://aka.ms/objective-sharpie
#
# This script ONLY binds Framework-Swift.h headers (the ObjC interface
# generated by the Swift compiler).  If a framework does not ship a
# Swift header it is skipped and a warning is logged.  Umbrella / plain-C
# headers (Framework.h) are never used because they produce incorrect
# bindings that silently diverge from the Swift API surface.

set -e

# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

ARTIFACTS_DIR="$PROJECT_ROOT/Datadog.MAUI.iOS.Binding/artifacts"
BINDINGS_DIR="$PROJECT_ROOT/Datadog.MAUI.iOS.Binding"
PLATFORM_DIR="ios-arm64_x86_64-simulator"  # Use simulator architecture for Sharpie compatibility

# ---------------------------------------------------------------------------
# Platform directory preference order
# Prefer the device slice for arm64 symbols; fall back to simulator.
# ---------------------------------------------------------------------------
PLATFORM_DIRS=(
    "ios-arm64_arm64e"
    "ios-arm64"
    "ios-arm64_x86_64-simulator"
)

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
if ! command -v sharpie &> /dev/null; then
    echo -e "${RED}Error: Objective Sharpie is not installed${NC}"
    echo "Install with:  brew install objectivesharpie"
    echo "  -- or --     https://aka.ms/objective-sharpie"
    exit 1
fi

echo -e "${CYAN}Objective Sharpie version: $(sharpie -v)${NC}"

if [ ! -d "$ARTIFACTS_DIR" ]; then
    echo -e "${RED}Error: Artifacts directory not found: $ARTIFACTS_DIR${NC}"
    echo -e "${YELLOW}Run ./download-ios-frameworks.sh first${NC}"
    exit 1
fi

# ---------------------------------------------------------------------------
# Xcode / SDK detection
#
# Try versioned Xcode installs first (15.x, 16.x, 26.x) then the default
# /Applications/Xcode.app.  Any Xcode that ships an iphoneos SDK will work;
# Sharpie 3.5+ is compatible with modern SDKs.
# ---------------------------------------------------------------------------
echo -e "${CYAN}Detecting Xcode / iOS SDK...${NC}"

XCODE_FOUND=false

for XCODE_PATTERN in /Applications/Xcode-15*.app /Applications/Xcode-16*.app /Applications/Xcode_26*.app /Applications/Xcode-26*.app /Applications/Xcode.app; do
    for XCODE_PATH in $XCODE_PATTERN; do
        if [ -d "$XCODE_PATH" ]; then
            XCODE_VERSION=$(defaults read "$XCODE_PATH/Contents/version" CFBundleShortVersionString 2>/dev/null || echo "unknown")
            echo -e "${GREEN}Using Xcode $XCODE_VERSION at $XCODE_PATH${NC}"
            export DEVELOPER_DIR="$XCODE_PATH/Contents/Developer"
            XCODE_FOUND=true
            break 2
        fi
    done
done

if [ "$XCODE_FOUND" = false ]; then
    echo -e "${YELLOW}Warning: No Xcode installation found, using xcode-select default${NC}"
fi

# Detect iOS SDK via Sharpie itself (more reliable than parsing xcodebuild)
SDK=$(sharpie xcode -sdks 2>/dev/null | grep '^sdk: iphoneos' | head -1 | awk '{print $2}')

if [ -z "$SDK" ]; then
    echo -e "${RED}Error: No iphoneos SDK found by Objective Sharpie${NC}"
    echo "Run 'sharpie xcode -sdks' to see available SDKs."
    exit 1
fi

# Automatically discover all XCFrameworks in the artifacts directory
echo -e "${CYAN}Discovering XCFrameworks in $ARTIFACTS_DIR...${NC}"
FRAMEWORKS=()
if [ -d "$ARTIFACTS_DIR" ]; then
    while IFS= read -r -d '' xcframework; do
        # Extract framework name (remove .xcframework extension)
        framework_name=$(basename "$xcframework" .xcframework)
        FRAMEWORKS+=("$framework_name")
        echo -e "  ${GREEN}Found:${NC} $framework_name"
    done < <(find "$ARTIFACTS_DIR" -maxdepth 1 -name "*.xcframework" -type d -print0 | sort -z)
else
    echo -e "${RED}Error: Artifacts directory not found: $ARTIFACTS_DIR${NC}"
    exit 1
fi

if [ ${#FRAMEWORKS[@]} -eq 0 ]; then
    echo -e "${RED}Error: No XCFrameworks found in $ARTIFACTS_DIR${NC}"
    echo -e "${YELLOW}Run 'make download-ios-frameworks' first to download the frameworks${NC}"
    exit 1
fi

echo -e "${GREEN}Found ${#FRAMEWORKS[@]} XCFrameworks to process${NC}"
echo -e "${CYAN}Using iOS SDK: $SDK${NC}\n"

for FRAMEWORK in "${FRAMEWORKS[@]}"; do
    ((CURRENT++))
    echo -e "${CYAN}[$CURRENT/$TOTAL] $FRAMEWORK${NC}"

    # --- Locate the framework directory (try each platform slice) ----------
    FRAMEWORK_PATH=""
    for PDIR in "${PLATFORM_DIRS[@]}"; do
        CANDIDATE="$ARTIFACTS_DIR/$FRAMEWORK.xcframework/$PDIR/$FRAMEWORK.framework"
        if [ -d "$CANDIDATE" ]; then
            FRAMEWORK_PATH="$CANDIDATE"
            break
        fi
    done

    if [ -z "$FRAMEWORK_PATH" ]; then
        MSG="$FRAMEWORK: xcframework directory not found under $ARTIFACTS_DIR/$FRAMEWORK.xcframework"
        echo -e "${RED}  ✗ $MSG${NC}"
        echo "ERROR: $MSG" >> "$LOG_FILE"
        ((FAILED++))
        echo ""
        continue
    fi

    # --- Locate the Swift-generated ObjC header -------------------------
    HEADERS_PATH="$FRAMEWORK_PATH/Headers"
    SWIFT_HEADER="$HEADERS_PATH/$FRAMEWORK-Swift.h"

    if [ ! -d "$HEADERS_PATH" ]; then
        MSG="$FRAMEWORK: No Headers/ directory in $FRAMEWORK_PATH (pure Swift module — no ObjC API surface)"
        echo -e "${YELLOW}  ⚠ SKIPPED — $MSG${NC}"
        echo "WARNING: $MSG" >> "$LOG_FILE"
        ((SKIPPED++))
        echo ""
        continue
    fi

    if [ ! -f "$SWIFT_HEADER" ]; then
        # List what IS in Headers/ for diagnostic context
        AVAILABLE_HEADERS=$(ls "$HEADERS_PATH" 2>/dev/null | tr '\n' ', ' | sed 's/,$//')
        MSG="$FRAMEWORK: Missing $FRAMEWORK-Swift.h (available headers: $AVAILABLE_HEADERS)"
        echo -e "${YELLOW}  ⚠ SKIPPED — Swift header not found${NC}"
        echo -e "${YELLOW}    Available headers: $AVAILABLE_HEADERS${NC}"
        echo -e "${YELLOW}    NOT falling back to umbrella header — it would produce incorrect bindings.${NC}"
        echo "WARNING: $MSG" >> "$LOG_FILE"
        ((SKIPPED++))
        echo ""
        continue
    fi

    # Determine binding project directory name
    BINDING_PROJECT_DIR="$BINDINGS_DIR/$FRAMEWORK"

    # Check if binding project directory exists
    if [ ! -d "$BINDING_PROJECT_DIR" ]; then
        echo -e "${RED}  ✗ Binding project directory not found: $BINDING_PROJECT_DIR${NC}"
        echo -e "${YELLOW}  ⚠ Skipping $FRAMEWORK (project doesn't exist)${NC}"
        continue
    fi

    # Strip "Datadog" prefix from framework name for cleaner C# namespaces
    # Examples: DatadogCore → Core, DatadogRUM → RUM, OpenTelemetryApi → OpenTelemetryApi
    if [[ "$FRAMEWORK" == Datadog* ]]; then
        NAMESPACE_SUFFIX="${FRAMEWORK#Datadog}"
    else
        NAMESPACE_SUFFIX="$FRAMEWORK"
    fi

    # Create temporary directory for Sharpie output
    TEMP_OUTPUT="/tmp/sharpie-$FRAMEWORK-$$"
    mkdir -p "$TEMP_OUTPUT"

    # Run Objective Sharpie
    echo -e "  Generating bindings with namespace: Datadog.iOS.$NAMESPACE_SUFFIX"
    sharpie bind \
        --output="$TEMP_OUTPUT" \
        --namespace="Datadog.iOS.$NAMESPACE_SUFFIX" \
        --sdk="$SDK" \
        -scope "$HEADERS_PATH" \
        "$HEADER_TO_BIND" \
        2>&1 | grep -v "warning:" || true

    # Copy generated files to binding project directory
    if [ -f "$TEMP_OUTPUT/ApiDefinitions.cs" ]; then
        # Rename ApiDefinitions.cs to ApiDefinition.cs (singular)
        cp "$TEMP_OUTPUT/ApiDefinitions.cs" "$BINDING_PROJECT_DIR/ApiDefinition.cs"
        echo -e "${GREEN}  ✓ Generated ApiDefinition.cs → $BINDING_PROJECT_DIR/ApiDefinition.cs${NC}"
    else
        SHARPIE_EXIT=$?
    fi

    if [ -f "$TEMP_OUTPUT/StructsAndEnums.cs" ]; then
        cp "$TEMP_OUTPUT/StructsAndEnums.cs" "$BINDING_PROJECT_DIR/StructsAndEnums.cs"
        echo -e "${GREEN}  ✓ Generated StructsAndEnums.cs → $BINDING_PROJECT_DIR/StructsAndEnums.cs${NC}"
    else
        MSG="$FRAMEWORK: Sharpie did not produce ApiDefinitions.cs (exit=$SHARPIE_EXIT, errors=$ERR_COUNT)"
        echo -e "${RED}  ✗ $MSG${NC}"
        echo -e "${RED}    See $SHARPIE_LOG for details${NC}"
        echo "ERROR: $MSG" >> "$LOG_FILE"
        ((FAILED++))
    fi

    # Clean up temporary directory
    rm -rf "$TEMP_OUTPUT"

    echo ""
done

echo -e "${GREEN}Binding generation complete!${NC}"
echo -e "${CYAN}Generated bindings have been written directly to binding project directories${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Review the generated ApiDefinition.cs and StructsAndEnums.cs files in each binding project"
echo "2. Look for [Verify] attributes that need manual attention"
echo "3. Test the bindings by building the projects"
echo "4. Commit the changes if everything looks good"
echo "4. Consolidate enums/structs into Datadog.MAUI.iOS.Binding/StructsAndEnums.cs"
echo "5. Build the iOS binding project: dotnet build Datadog.MAUI.iOS.Binding/Datadog.MAUI.iOS.Binding.csproj"
